### ISSUE TITLE
AssertionError: Could not find core.a using ESP32 DevKit

### ISSUE THREAD

**Issue by aggelosmots** [SterlingPeet/arduino-cli-cmake-wrapper#11]
I'm following the [Led blinker example](https://github.com/fprime-community/fprime-arduino-led-blinker/blob/main/docs/arduino-cli-install.md#arduino-cli-installation-guide). When I use the command `fprime-util generate` I get the following error

```
$ fprime-util generate
[INFO] Generating build directory at: /home/aggelosmots/Desktop/eps32-fprime/led-blinker/build-fprime-automatic-esp32
[INFO] Using toolchain file /home/aggelosmots/Desktop/eps32-fprime/led-blinker/fprime-arduino/cmake/toolchain/esp32.cmake for platform default
WARNING:arduino_cli_cmake_wrapper.parser:Unknown sections detected with titles: Creating esp32 image...,Creating esp32 image...
[ERROR] AssertionError occurred. Could not find core.a
Traceback (most recent call last):
  File "/home/aggelosmots/miniconda3/envs/led-blinker/bin/arduino-cli-wrapper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aggelosmots/miniconda3/envs/led-blinker/lib/python3.11/site-packages/arduino_cli_cmake_wrapper/cli.py", line 241, in main
    output_data, cache_path = assemble_output_data(
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aggelosmots/miniconda3/envs/led-blinker/lib/python3.11/site-packages/arduino_cli_cmake_wrapper/cli.py", line 224, in assemble_output_data
    return data, sketch_cache(stages)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/aggelosmots/miniconda3/envs/led-blinker/lib/python3.11/site-packages/arduino_cli_cmake_wrapper/miner.py", line 141, in sketch_cache
    assert core_tokens, "Could not find core.a"
AssertionError: Could not find core.a
CMake Error at fprime-arduino/cmake/toolchain/support/arduino-wrapper.cmake:72 (message):
-- Configuring incomplete, errors occurred!
  Could not run 'arduino-cli' please install 'arduino-cli' and board
  'esp32:esp32:esp32'.
Call Stack (most recent call first):
  fprime-arduino/cmake/toolchain/support/arduino-support.cmake:43 (run_arduino_wrapper)
  fprime-arduino/cmake/toolchain/support/arduino-support.cmake:201 (set_arduino_build_settings)
  fprime-arduino/cmake/toolchain/esp32.cmake:18 (include)
  /usr/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:5 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
[ERROR] CMake erred with return code 1. Partial build cache remains. Run purge to clean-up.
 ```

I tried other toolchains like for the teensy series and everything worked fine

**Comment by SterlingPeet** [comment]
Currently this tool struggles to scrape the ESP32 build process.  However, you have mentioned ``fprime-arduino``, and the latest public beta version has a toolchain file that skips invoking this tool and fills in the correct information in a static way.  Does the current beta code work for you?
